email: andryusha@andryusha.com
title: Андрей Маслов
description: Разработчик сайтов и сервисов из Evrone
url: ""
baseurl: ""
permalink: /:title
lang: ru
timezone: Europe/Moscow
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
